"""Utilities for exporting Focus Assistant data to Obsidian-friendly Markdown."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional

from config import config
from storage import storage, Task
from tasks import task_manager


@dataclass
class ExportSection:
    """Represents a logical task grouping in the Markdown export."""

    title: str
    tasks: List[Task]


def export_tasks_to_markdown(
    include_completed: bool = False,
    output_path: Optional[Path] = None,
) -> Path:
    """
    Export the current task board to an Obsidian-friendly Markdown file.

    Args:
        include_completed: Whether to include a recently completed section.
        output_path: Optional override for where to write the file.

    Returns:
        Path to the generated markdown file.
    """

    # Determine destination inside the journal directory so existing symlinks work.
    if output_path is None:
        output_path = config.journal_dir / "TASKS.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    today_tasks = _sorted_tasks(task_manager.get_today_tasks())
    upcoming_tasks = _sorted_tasks(
        task_manager.get_upcoming_tasks(), key=lambda t: t.due_date or datetime.max
    )
    inbox_tasks = _sorted_tasks(task_manager.get_inbox_tasks(), key=lambda t: t.created_at)

    sections: List[ExportSection] = [
        ExportSection("📌 Today", today_tasks),
        ExportSection("📅 Upcoming", upcoming_tasks),
        ExportSection("📥 Inbox", inbox_tasks),
    ]

    completed_tasks: List[Task] = []
    if include_completed:
        completed_tasks = [
            task for task in storage.load_tasks() if task.completed and task.completed_at
        ]
        completed_tasks.sort(key=lambda t: t.completed_at, reverse=True)
        completed_tasks = completed_tasks[:20]
        sections.append(ExportSection("✅ Recently Completed", completed_tasks))

    project_lookup = {project.id: project.name for project in storage.load_projects()}
    generated_at = datetime.now()

    lines: List[str] = []
    lines.extend(_markdown_header(generated_at))
    lines.append("# Focus Assistant Tasks")
    lines.append("")
    lines.append(
        "> This file is auto-generated by `./focus export obsidian`. "
        "Treat it as read-only—re-run the command to refresh."
    )
    lines.append("")
    lines.append(f"_Last updated: {generated_at.strftime('%A, %B %d, %Y at %I:%M %p')}_")
    lines.append("")

    for section in sections:
        lines.extend(_render_section(section, project_lookup))

    lines.append("---")
    lines.append("Export generated by Focus Assistant")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def _markdown_header(generated_at: datetime) -> List[str]:
    """Frontmatter for Obsidian / Dataview compatibility."""
    return [
        "---",
        "title: Focus Assistant Tasks",
        f"generated_at: {generated_at.isoformat()}",
        "tags: [focus, tasks, export]",
        "---",
        "",
    ]


def _render_section(section: ExportSection, project_lookup: dict[str, str]) -> List[str]:
    """Render a single section worth of tasks."""
    lines = [f"## {section.title} ({len(section.tasks)})", ""]

    if not section.tasks:
        lines.append("_No tasks in this section._")
        lines.append("")
        return lines

    for task in section.tasks:
        lines.extend(_render_task(task, project_lookup))

    lines.append("")
    return lines


def _render_task(task: Task, project_lookup: dict[str, str]) -> List[str]:
    """Format a single task entry."""
    checkbox = "x" if task.completed else " "
    safe_text = task.text.replace("\n", " ").strip()

    due_part = ""
    if task.due_date:
        due_part = task.due_date.strftime("%a, %b %d")
        due_part = f" _(due {due_part})_"

    project_part = ""
    if task.project_id and task.project_id in project_lookup:
        project_part = f" _(project: {project_lookup[task.project_id]})_"

    meta_line = (
        f"  - status:: {task.status}"
        f"{' | completed:: ' + task.completed_at.strftime('%Y-%m-%d %H:%M') if task.completed and task.completed_at else ''}"
        f"{' | created:: ' + task.created_at.strftime('%Y-%m-%d %H:%M') if task.created_at else ''}"
        f" | id:: {task.id}"
    )

    return [
        f"- [{checkbox}] {safe_text}{due_part}{project_part}",
        meta_line,
    ]


def _sorted_tasks(tasks: Iterable[Task], key=None) -> List[Task]:
    """Return a stable list sorted by due date and creation time."""
    if key is None:
        key = lambda t: (t.due_date or datetime.max, t.created_at)
    return sorted(tasks, key=key)


